spring.application.name=learnspringboot
spring.sql.init.mode=always
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase?options=-c%20timezone=UTC
spring.datasource.username=myuser
spring.datasource.password=secret